### ISSUE TITLE
Horizontally center the home image for tablet and mobile.

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/motley#130]
<a href="https://github.com/abhishek97"><img src="https://avatars1.githubusercontent.com/u/8109774?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [abhishek97](https://github.com/abhishek97)**
_Sunday May 13, 2018 at 11:35 GMT_
_Originally opened as https://github.com/coding-blocks/codingblocks.online.projectx/issues/30_

----

![screen shot 2018-05-13 at 5 05 28 pm](https://user-images.githubusercontent.com/8109774/39966829-c472cfde-56cf-11e8-8587-742285c2b086.png)

**Comment by hereisnaman** [comment]
@abhishek97 
motley PR: https://github.com/coding-blocks/motley/pull/139
ProjectX (required classes): https://github.com/coding-blocks/codingblocks.online.projectx/pull/67 

SS: ![screen shot 2018-05-15 at 12 24 49 pm](https://user-images.githubusercontent.com/22571395/40041319-2c208a60-583b-11e8-917a-6af5a04d3c75.png)

**Comment by vdvibhu20** [comment]
done #140
