### ISSUE TITLE
Horizontally center the logo for tablet and mobile

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/motley#131]
<a href="https://github.com/architkshk"><img src="https://avatars1.githubusercontent.com/u/5001704?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [architkshk](https://github.com/architkshk)**
_Monday May 14, 2018 at 19:55 GMT_
_Originally opened as https://github.com/coding-blocks/codingblocks.online.projectx/issues/46_

----

**Comment by abhisheksh02** [comment]
done #140
