### ISSUE TITLE
Add Skeleton cards to represent loading state for course-cards

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/motley#134]
It is required to be first implemented in motley before https://github.com/coding-blocks/codingblocks.online.projectx/issues/29

**Comment by hereisnaman** [comment]
@abhishek97 these are the PRs
ProjectX: https://github.com/coding-blocks/codingblocks.online.projectx/pull/66/
Motley: https://github.com/coding-blocks/motley/pull/138

**Comment by hereisnaman** [comment]
@abhishek97 anything you need more?

**Comment by lazy-god** [comment]
Done in #233
