### ISSUE TITLE
Refactor Components

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/motley#142]
If you look at the `examples` directory, you'll see that currently, we have only one component -> `nav-bar.hbs`. Ideally, we would want to move each isolated component to separate hbs file and there use it as partial (the `{{> nav-bar}}` syntax) in all the pages(`views`)

Components to refactor (will update the list):

- [ ] Course Card
- [ ] Footer
- [ ] Button
- [ ] Accordion

BOSS: Bounty applies to each component refactored, i.e 100 Bounty points each. Make separate PR.

**Comment by ankurg22** [comment]
There are multiple types of course cards. Do I need to make specific hbs file for each?

**Comment by witty123** [comment]
This issue is on hold for now.
