### ISSUE TITLE
Broken Design on Choose Address Page

### ISSUE THREAD

**Issue by firefinchdev** [coding-blocks/motley#162]
![screenshot from 2018-06-01 14-38-31](https://user-images.githubusercontent.com/26357501/40832825-e4ead02a-65a9-11e8-960c-0cfadf2551f4.png)

**Comment by firefinchdev** [comment]
Screen Resolution: 1366 x 768

**Comment by aayusharora** [comment]
![screen shot 2018-06-01 at 3 15 17 pm](https://user-images.githubusercontent.com/12194719/40834509-a74936f8-65ae-11e8-9453-f888cb468a8e.png)

**Comment by aayusharora** [comment]
works perfect here !!

**Comment by aayusharora** [comment]
![screen shot 2018-06-01 at 3 18 01 pm](https://user-images.githubusercontent.com/12194719/40834644-03db6904-65af-11e8-9beb-9636bdc4a268.png)
