### ISSUE TITLE
Navbar overflow 

### ISSUE THREAD

**Issue by vdvibhu20** [coding-blocks/motley#187]
Nav bar overflows at screen width less than 921px.

![screen shot 2018-06-18 at 1 18 24 pm](https://user-images.githubusercontent.com/18213029/41524572-a09b7a0a-72fb-11e8-839b-28eef46868a4.png)
![screen shot 2018-06-18 at 1 18 37 pm](https://user-images.githubusercontent.com/18213029/41524575-a14bb1a4-72fb-11e8-946e-f2d72d120d55.png)
![screen shot 2018-06-18 at 1 18 58 pm](https://user-images.githubusercontent.com/18213029/41524576-a18d76f2-72fb-11e8-90ff-ea4406b91bb3.png)

**Comment by Rishabh570** [comment]
@vdvibhu20 I would like to work on it.
