### ISSUE TITLE
Modal for feedback component

### ISSUE THREAD

**Issue by witty123** [coding-blocks/motley#253]
Designs will be shared with people who want to work on this issue

**Comment by lazy-god** [comment]
I will be working on this, please share the design darshpratap@gmail.com

**Comment by VibhorCodecianGupta** [comment]
@witty123 I'll work on this, please share designs at vibhordelgupta@gmail.com

**Comment by firefinchdev** [comment]
@witty123 I will work on this, pls share designs.
anirudhgupta281998@gmail.com

**Comment by firefinchdev** [comment]
@witty123 Done #255 
Pls Review.

**Comment by VibhorCodecianGupta** [comment]
@witty123 designs?

**Comment by witty123** [comment]
I had shared them with @lazy-god earlier. Forgot to share it with @VibhorCodecianGupta and @firefinchdev. I hope everyone has the designs now.
