### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by witty123** [coding-blocks/motley#268]
Refactor motley to follow ITCSS.

Elements layer should only have html elements. 
Extra objects present in elements layer (ex searchbox) should go into object layer.
What we have in object layer now is a mixture of objects and components. Create a separate layer for components. 
Classes currently prefixed with `o-` in object layer must be prefixed with `c-` in the component layer.
Take help from this blog to decide what should be an object and what should be a component.
https://www.xfive.co/blog/itcss-scalable-maintainable-css-architecture/

**Comment by firefinchdev** [comment]
@witty123 
Done. Pls Review. #273

**Comment by VibhorCodecianGupta** [comment]
#275 @witty123 
Done. Earliest usable commit.

**Comment by witty123** [comment]
We have to reflect the DOM changes in online project x and in accounts as well. https://github.com/coding-blocks/codingblocks.online.projectx/issues/268
https://github.com/coding-blocks/oneauth/issues/354
