### ISSUE TITLE
IDE mobile view

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/motley#276]
Make mobile view for `code-challenge` content for online.codingblocks.com 

Only the problem/submissions/leaderboard should be visible for mobile. Basically this part

<img width="1440" alt="screen_shot_2018-08-13_at_6_50_10_pm" src="https://user-images.githubusercontent.com/8109774/44034086-e16da526-9f29-11e8-8948-d717bc846e0e.png">

Also a text - "To solve this problem, please use a desktop."

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 @vdvibhu20 is this done or does it need to be?

**Comment by theParadoxicalWizard** [comment]
@abhishek97 can you please explain?
Also i am not able to see the code challenge content...

**Comment by RachitBansal** [comment]
Can't find `code-challenge` 

![chrome_ge1V3i5CeK](https://user-images.githubusercontent.com/18123052/60771862-7b7ccf00-a10b-11e9-8e90-1b2c9868d544.png)

**Comment by mnb27** [comment]
Can I work on this issue?

**Comment by vdvibhu20** [comment]
This view has been changed.
