### ISSUE TITLE
Fix travis build

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/motley#329]
The travis build is failing, probably due to different node version. Node 8 LTS should be used build this project.

**Comment by sourabh1031** [comment]
@abhishek97 can i try on this

**Comment by abhishek97** [comment]
Sure. Go ahead

**Comment by sourabh1031** [comment]
will i get a bounty for this pr if you merge it after boss starts :D

**Comment by sourabh1031** [comment]
@abhishek97 can i claim bounty for this

**Comment by abhishek97** [comment]
I'm afraid you cannot. Since this was merged before 15th May.
